apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-bot-config
  namespace: appointment-bot
data:
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Database settings
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "appointment_bot"
  POSTGRES_USER: "postgres"
  
  # Neo4j settings
  NEO4J_USER: "neo4j"
  
  # Redis settings
  REDIS_PORT: "6379"
  
  # Vector database
  VECTOR_DB_PROVIDER: "pinecone"
  EMBEDDING_PROVIDER: "openai"
  EMBEDDING_MODEL: "text-embedding-ada-002"
  EMBEDDING_DIMENSION: "1536"
  
  # LLM settings
  LLM_PROVIDER: "openai"
  LLM_MODEL: "gpt-4-turbo-preview"
  LLM_TEMPERATURE: "0.7"
  LLM_MAX_TOKENS: "1000"
  
  # Business settings
  BUSINESS_TIMEZONE: "UTC"
  DEFAULT_APPOINTMENT_DURATION: "60"
  BOOKING_ADVANCE_DAYS: "30"
  CANCELLATION_HOURS: "24"
  
  # RAG settings
  RAG_CHUNK_SIZE: "1000"
  RAG_CHUNK_OVERLAP: "200"
  RAG_TOP_K: "5"
  RAG_SIMILARITY_THRESHOLD: "0.7"
  
  # Graph settings
  GRAPH_BATCH_SIZE: "100"
  GRAPH_MAX_TRAVERSAL_DEPTH: "3"
  RECOMMENDATION_LIMIT: "10"
  
  # Celery settings
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"