apiVersion: v1
kind: Secret
metadata:
  name: appointment-bot-secrets
  namespace: appointment-bot
type: Opaque
stringData:
  # Database passwords (base64 encoded in actual deployment)
  POSTGRES_PASSWORD: "change-this-password"
  NEO4J_PASSWORD: "change-this-password"
  REDIS_PASSWORD: ""
  
  # API keys (set these in actual deployment)
  OPENAI_API_KEY: "sk-your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  PINECONE_API_KEY: "your-pinecone-api-key"
  
  # Telegram bot
  TELEGRAM_BOT_TOKEN: "your-telegram-bot-token"
  TELEGRAM_WEBHOOK_SECRET: "your-webhook-secret"
  
  # Application secrets
  SECRET_KEY: "your-super-secret-application-key"
  
  # Business settings
  BUSINESS_NAME: "Your Business Name"

---
apiVersion: v1
kind: Secret
metadata:
  name: appointment-bot-db-secrets
  namespace: appointment-bot
type: Opaque
stringData:
  # Database hosts (will be set based on your infrastructure)
  POSTGRES_HOST: "postgres-service"
  NEO4J_URI: "bolt://neo4j-service:7687"
  REDIS_HOST: "redis-service"
  
  # External services
  PINECONE_ENVIRONMENT: "your-pinecone-environment"
  PINECONE_INDEX_NAME: "appointment-bot-prod"